"use client";

import { useState } from "react";

type Tab = "overview" | "tables";
type Table = { id: string; label: string; zone: string };
const initialTables: Table[] = [{ id: "01", label: "01", zone: "Основний зал" }, { id: "02", label: "02", zone: "Основний зал" }, { id: "03", label: "03", zone: "Основний зал" }, { id: "04", label: "04", zone: "Основний зал" }, { id: "t1", label: "Т1", zone: "Тераса" }];
const kpis = [["184 240,00 ₴", "Виручка", "+12,4%"], ["71%", "Оплат через QR", "+8,2%"], ["1 420,00 ₴", "Середній чек", "+4,1%"], ["12 430,00 ₴", "Чайові", "+18,7%"]];

export function OwnerExperience() {
  const [tab, setTab] = useState<Tab>("overview"); const [tables, setTables] = useState(initialTables); const [showAdd, setShowAdd] = useState(false); const [showQr, setShowQr] = useState<Table | null>(null); const [label, setLabel] = useState("");
  const addTable = () => { const normalized = label.trim(); if (!normalized) return; setTables((current) => [...current, { id: crypto.randomUUID(), label: normalized, zone: "Основний зал" }]); setLabel(""); setShowAdd(false); };
  return <section className="screen owner">
    <p className="eyebrow">СЬОГОДНІ · 20 СЕРПНЯ</p><div className="owner-heading"><h1>{tab === "overview" ? "Огляд" : "Столи та QR"}</h1><button className="date-button">Сьогодні⌄</button></div>
    <div className="owner-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Огляд</button><button className={tab === "tables" ? "active" : ""} onClick={() => setTab("tables")}>Столи</button></div>
    {tab === "overview" ? <Overview /> : <Tables tables={tables} onAdd={() => setShowAdd(true)} onQr={setShowQr} />}
    {showAdd && <div className="sheet-backdrop" role="presentation"><section className="bottom-sheet" role="dialog" aria-modal="true" aria-labelledby="new-table-title"><div className="sheet-handle" /><h2 id="new-table-title">Новий стіл</h2><p>Створимо QR-код для основного залу.</p><label>Назва столу<input autoFocus value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Наприклад, 07" onKeyDown={(event) => event.key === "Enter" && addTable()} /></label><button className="primary full" onClick={addTable}>Створити стіл</button><button className="cancel" onClick={() => setShowAdd(false)}>Скасувати</button></section></div>}
    {showQr && <div className="sheet-backdrop" role="presentation"><section className="bottom-sheet qr-sheet" role="dialog" aria-modal="true" aria-labelledby="qr-title"><div className="sheet-handle" /><p className="eyebrow">QR ДЛЯ ДРУКУ</p><h2 id="qr-title">Стіл {showQr.label}</h2><div className="qr-art" aria-label="Демонстрація QR-коду"><span /></div><strong>GOODMAN</strong><p>Наведіть камеру, щоб переглянути та сплатити рахунок.</p><button className="primary full" onClick={() => setShowQr(null)}>Готово</button><button className="cancel" onClick={() => setShowQr(null)}>Перевипустити QR</button></section></div>}
  </section>;
}
function Overview() { return <><div className="kpis">{kpis.map(([value, label, trend]) => <article className="kpi" key={label}><span>{label}</span><strong>{value}</strong><small>↑ {trend}</small></article>)}</div><article className="card revenue-card"><div><p className="label">QR-ВИРУЧКА</p><strong>131 620,00 ₴</strong></div><div className="chart" aria-label="Графік QR-виручки за тиждень">{[40,66,45,82,61,94,70].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-days"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Нд</span></div></article><article className="card staff-card"><div className="section-title"><b>Офіціанти</b><button>Усі →</button></div><Staff no="1" initials="АК" name="Анна Коваленко" sales="42 400,00 ₴" tips="4 210,00 ₴" /><Staff no="2" initials="МБ" name="Максим Бойко" sales="38 100,00 ₴" tips="3 820,00 ₴" /><Staff no="3" initials="ІМ" name="Іван Мельник" sales="31 200,00 ₴" tips="2 940,00 ₴" /></article></> }
function Tables({ tables, onAdd, onQr }: { tables: Table[]; onAdd: () => void; onQr: (table: Table) => void }) { return <><div className="table-summary"><span>{tables.length} столів активні</span><button className="primary" onClick={onAdd}>＋ Додати</button></div><p className="label list-label">ОСНОВНИЙ ЗАЛ</p><div className="owner-table-list">{tables.filter((table) => table.zone === "Основний зал").map((table) => <button key={table.id} onClick={() => onQr(table)}><span className="table-icon">▦</span><span>Стіл {table.label}<small>QR активний · натисніть для перегляду</small></span><b>›</b></button>)}</div><p className="label list-label">ТЕРАСА</p><div className="owner-table-list">{tables.filter((table) => table.zone === "Тераса").map((table) => <button key={table.id} onClick={() => onQr(table)}><span className="table-icon">▦</span><span>Стіл {table.label}<small>QR активний · натисніть для перегляду</small></span><b>›</b></button>)}</div></> }
function Staff({ no, initials, name, sales, tips }: { no: string; initials: string; name: string; sales: string; tips: string }) { return <div className="owner-staff"><span className="rank">{no}</span><span className="staff-avatar">{initials}</span><span>{name}<small>{sales} продажів</small></span><strong>{tips}<small>чайові</small></strong></div>; }
