"use client";

import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import type { PaymentConfigResponse, StaffSessionResponse } from "@fastpay/contracts";
import { clearOwnerSession, ownerApi, readOwnerSession, storeOwnerSession } from "../lib/owner-api";
import { StaffApiError } from "../lib/staff-api";

type Tab = "overview" | "tables" | "payments";
type AuthMode = "login" | "register";
type OwnerTable = { id: string; label: string; zone: string; floorId?: string; qrToken?: string };
const previewTables: OwnerTable[] = [{ id: "01", label: "01", zone: "Основний зал" }, { id: "02", label: "02", zone: "Основний зал" }, { id: "03", label: "03", zone: "Основний зал" }, { id: "t1", label: "Т1", zone: "Тераса" }];

export function OwnerExperience() {
  const [tab, setTab] = useState<Tab>("overview"); const [session, setSession] = useState<StaffSessionResponse | null>(null); const [hydrated, setHydrated] = useState(false); const [tables, setTables] = useState<OwnerTable[]>(previewTables); const [venueId, setVenueId] = useState<string>(); const [primaryFloorId, setPrimaryFloorId] = useState<string>(); const [showAdd, setShowAdd] = useState(false); const [showQr, setShowQr] = useState<OwnerTable | null>(null); const [label, setLabel] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const loadStructure = async (activeSession: StaffSessionResponse) => { setLoading(true); setError(""); try { const venue = (await ownerApi.listVenues(activeSession.token)).venues[0]; if (!venue) { setTables([]); return; } setVenueId(venue.id); const floors = await ownerApi.listFloors(venue.id, activeSession.token); setPrimaryFloorId(floors.floors[0]?.id); const grouped = await Promise.all(floors.floors.map(async floor => (await ownerApi.listTables(floor.id, activeSession.token)).tables.map(table => ({ id: table.id, label: table.label, zone: floor.name, floorId: floor.id, qrToken: table.qrToken })))); setTables(grouped.flat()); } catch (requestError) { setError(requestError instanceof StaffApiError ? requestError.message : "Не вдалося завантажити заклад"); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { const saved = readOwnerSession(); setSession(saved); setHydrated(true); if (saved) void loadStructure(saved); }, 0); return () => window.clearTimeout(timer); }, []);
  const addTable = async () => { const normalized = label.trim(); if (!normalized || !session) return; setLoading(true); setError(""); try { let floorId = primaryFloorId; let zone = "Основний зал"; if (!floorId) { const venue = (await ownerApi.listVenues(session.token)).venues[0]; if (!venue) throw new Error("Не знайдено заклад для створення залу"); const floor = await ownerApi.createFloor(venue.id, zone, session.token); floorId = floor.id; zone = floor.name; setPrimaryFloorId(floor.id); } const table = await ownerApi.createTable(floorId, normalized, session.token); setTables(current => [...current, { id: table.id, label: table.label, zone, floorId: table.floorId, qrToken: table.qrToken }]); setLabel(""); setShowAdd(false); } catch (requestError) { setError(requestError instanceof StaffApiError || requestError instanceof Error ? requestError.message : "Не вдалося створити стіл"); } finally { setLoading(false); } };
  const rotateQr = async () => { if (!session || !showQr?.qrToken) return; setLoading(true); setError(""); try { const updated = await ownerApi.rotateQr(showQr.id, session.token); setShowQr({ ...showQr, qrToken: updated.qrToken }); setTables(current => current.map(table => table.id === updated.id ? { ...table, qrToken: updated.qrToken } : table)); } catch (requestError) { setError(requestError instanceof StaffApiError ? requestError.message : "Не вдалося перевипустити QR"); } finally { setLoading(false); } };
  if (!hydrated) return <section className="screen state"><p className="eyebrow">RIMVO</p><h1>Завантажуємо кабінет…</h1></section>;
  if (!session) return <OwnerAccess onSession={next => { storeOwnerSession(next); setSession(next); void loadStructure(next); }} />;
  const live = Boolean(venueId);
  const title = tab === "overview" ? "Огляд" : tab === "tables" ? "Столи та QR" : "Приймання оплат";
  return <section className="screen owner"><div className="owner-ident"><div><p className="eyebrow">RIMVO · КАБІНЕТ ЗАКЛАДУ</p><div className="owner-heading"><h1>{title}</h1></div></div><button className="owner-logout" onClick={() => { clearOwnerSession(); setSession(null); setVenueId(undefined); setTables(previewTables); }}>Вийти</button></div><div className="owner-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Огляд</button><button className={tab === "tables" ? "active" : ""} onClick={() => setTab("tables")}>Столи</button><button className={tab === "payments" ? "active" : ""} onClick={() => setTab("payments")}>Оплата</button></div>{error && <p className="form-error" role="alert">{error}</p>}{tab === "overview" && <Overview live={live} />}{tab === "tables" && <Tables tables={tables} live={live} loading={loading} onAdd={() => setShowAdd(true)} onQr={setShowQr} />}{tab === "payments" && <PaymentSettings venueId={venueId} token={session.token} />}{showAdd && <div className="sheet-backdrop" role="presentation"><section className="bottom-sheet" role="dialog" aria-modal="true" aria-labelledby="new-table-title"><div className="sheet-handle" /><h2 id="new-table-title">Новий стіл</h2><p>{primaryFloorId ? "Створимо QR-код для основного залу." : "Перший стіл автоматично створить «Основний зал»."}</p><label>Назва столу<input autoFocus value={label} onChange={event => setLabel(event.target.value)} placeholder="Наприклад, 07" onKeyDown={event => event.key === "Enter" && void addTable()} /></label><button className="primary full" disabled={loading || !label.trim()} onClick={() => void addTable()}>{loading ? "Створюємо…" : "Створити стіл"}</button><button className="cancel" onClick={() => setShowAdd(false)}>Скасувати</button></section></div>}{showQr && <QrSheet table={showQr} loading={loading} onClose={() => setShowQr(null)} onRotate={() => void rotateQr()} />}</section>;
}

function PaymentSettings({ venueId, token }: { venueId?: string; token: string }) {
  const [config, setConfig] = useState<PaymentConfigResponse | null>(null); const [secret, setSecret] = useState(""); const [loading, setLoading] = useState(Boolean(venueId)); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { if (!venueId) return; let mounted = true; void ownerApi.getPaymentConfig(venueId, token).then(value => mounted && setConfig(value)).catch(requestError => { if (mounted && !(requestError instanceof StaffApiError && requestError.code === "PAYMENT_CONFIG_NOT_FOUND")) setError(requestError instanceof Error ? requestError.message : "Не вдалося завантажити налаштування"); }).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, [venueId, token]);
  const save = async () => { if (!venueId || !secret.trim()) return; setSaving(true); setError(""); setSuccess(""); try { const next = await ownerApi.setPaymentConfig(venueId, { provider: "fake", credentials: secret.trim() }, token); setConfig(next); setSecret(""); setSuccess("Підключення перевірено. Секрет не зберігається у браузері."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Не вдалося перевірити підключення"); } finally { setSaving(false); } };
  if (!venueId) return <article className="card owner-empty"><p className="label">ПЛАТІЖНА ІНТЕГРАЦІЯ</p><b>Створіть заклад, щоб увімкнути оплату.</b><p>Після реєстрації тут з’явиться безпечне підключення платіжного провайдера.</p></article>;
  return <div className="payment-settings"><article className="payment-status"><span className={config?.configured ? "status-check ready" : "status-check"}>{config?.configured ? "✓" : "!"}</span><div><p className="label">СТАТУС ЕКВАЙРИНГУ</p><b>{loading ? "Перевіряємо…" : config?.configured ? "Підключено" : "Не підключено"}</b><small>{config?.configured ? "Остання перевірка виконана успішно" : "Оплата гостя поки недоступна"}</small></div></article><article className="card provider-card"><p className="label">ПРОВАЙДЕР</p><div className="provider-name"><span>R</span><div><b>Rimvo test gateway</b><small>Тестове середовище для перевірки платіжного сценарію</small></div></div><div className="provider-note"><b>Перед запуском</b><p>Реальний еквайринг підключається після sandbox-ключів і перевірки webhook-підпису.</p></div><label>Секрет підключення<input type="password" value={secret} onChange={event => setSecret(event.target.value)} placeholder={config?.configured ? "Введіть новий секрет, щоб замінити" : "Введіть тестовий секрет"} autoComplete="new-password" /></label>{error && <p className="form-error" role="alert">{error}</p>}{success && <p className="form-success" role="status">{success}</p>}<button className="primary full" disabled={saving || !secret.trim()} onClick={() => void save()}>{saving ? "Перевіряємо…" : config?.configured ? "Оновити підключення" : "Перевірити та підключити"}</button></article></div>;
}

function OwnerAccess({ onSession }: { onSession: (session: StaffSessionResponse) => void }) { const [mode, setMode] = useState<AuthMode>("login"); const [organizationName, setOrganizationName] = useState(""); const [venueName, setVenueName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const submit = async () => { setLoading(true); setError(""); try { const next = mode === "register" ? await ownerApi.register({ organizationName, venueName, email, password }) : await ownerApi.login({ email, password }); if (next.staff.role !== "owner" && next.staff.role !== "manager") throw new Error("Цей акаунт не має доступу до кабінету власника"); onSession(next); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Не вдалося увійти"); } finally { setLoading(false); } }; return <section className="screen owner"><p className="eyebrow">RIMVO · КАБІНЕТ ЗАКЛАДУ</p><h1>{mode === "login" ? "Увійти до кабінету" : "Створити заклад"}</h1><p>Налаштуйте зали, столи та QR-коди в одному місці.</p><div className="card">{mode === "register" && <><label>Назва компанії<input value={organizationName} onChange={event => setOrganizationName(event.target.value)} placeholder="Rimvo Restaurant Group" /></label><label>Перше заведение<input value={venueName} onChange={event => setVenueName(event.target.value)} placeholder="GOODMAN" /></label></>}<label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" /></label><label>Пароль<input type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete={mode === "login" ? "current-password" : "new-password"} /></label>{error && <p role="alert">{error}</p>}<button className="primary full" disabled={loading || !email || !password || (mode === "register" && (!organizationName || !venueName))} onClick={() => void submit()}>{loading ? "Зачекайте…" : mode === "login" ? "Увійти" : "Створити кабінет"}</button></div><button className="link" onClick={() => setMode(current => current === "login" ? "register" : "login")}>{mode === "login" ? "Новий заклад? Зареєструватися" : "Вже є кабінет? Увійти"}</button></section>; }
function Overview({ live }: { live: boolean }) { const items = live ? [["—", "Виручка", "з’явиться після оплат"], ["—", "Оплат через QR", "збираємо дані"], ["—", "Середній чек", "збираємо дані"], ["—", "Чайові", "збираємо дані"]] : [["184 240,00 ₴", "Виручка", "+12,4%"], ["71%", "Оплат через QR", "+8,2%"], ["1 420,00 ₴", "Середній чек", "+4,1%"], ["12 430,00 ₴", "Чайові", "+18,7%"]]; return <><div className="kpis">{items.map(([value, label, trend]) => <article className="kpi" key={label}><span>{label}</span><strong>{value}</strong><small>{live ? trend : `↑ ${trend}`}</small></article>)}</div>{live ? <article className="card"><p className="label">АНАЛІТИКА</p><b>Перші показники з’являться після підтверджених оплат.</b><p>Rimvo не підміняє статистику демонстраційними цифрами у вашому кабінеті.</p></article> : <article className="card revenue-card"><div><p className="label">QR-ВИРУЧКА</p><strong>131 620,00 ₴</strong></div><div className="chart" aria-label="Графік QR-виручки за тиждень">{[40,66,45,82,61,94,70].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></article>}</> }
function Tables({ tables, live, loading, onAdd, onQr }: { tables: OwnerTable[]; live: boolean; loading: boolean; onAdd: () => void; onQr: (table: OwnerTable) => void }) { const zones = [...new Set(tables.map(table => table.zone))]; return <><div className="table-summary"><span>{loading ? "Оновлюємо…" : `${tables.length} столів ${live ? "активні" : "у preview"}`}</span><button className="primary" onClick={onAdd}>＋ Додати</button></div>{zones.length === 0 && <article className="card"><b>Ще немає залів</b><p>Створіть перший зал у налаштуваннях закладу, потім додайте столи.</p></article>}{zones.map(zone => <div key={zone}><p className="label list-label">{zone.toUpperCase()}</p><div className="owner-table-list">{tables.filter(table => table.zone === zone).map(table => <button key={table.id} onClick={() => onQr(table)}><span className="table-icon">▦</span><span>Стіл {table.label}<small>{live ? "QR активний · натисніть для перегляду" : "Preview · QR буде активний після підключення"}</small></span><b>›</b></button>)}</div></div>)}</> }
function QrSheet({ table, loading, onClose, onRotate }: { table: OwnerTable; loading: boolean; onClose: () => void; onRotate: () => void }) { const url = table.qrToken ? `${window.location.origin}/t/${table.qrToken}` : ""; return <div className="sheet-backdrop" role="presentation"><section className="bottom-sheet qr-sheet" role="dialog" aria-modal="true" aria-labelledby="qr-title"><div className="sheet-handle" /><p className="eyebrow">QR ДЛЯ ДРУКУ</p><h2 id="qr-title">Стіл {table.label}</h2>{table.qrToken ? <div className="qr-art qr-live"><QRCodeSVG value={url} size={180} level="M" includeMargin aria-label={`QR-код для столу ${table.label}`} /></div> : <div className="qr-art" aria-label="Preview QR-коду"><span /></div>}<strong>RIMVO</strong><p>{table.qrToken ? "Сканування веде гостя до поточного рахунку." : "Це preview-стіл: створіть його у live-залі, щоб отримати QR."}</p>{table.qrToken && <><button className="secondary full" onClick={() => void navigator.clipboard.writeText(url)}>Скопіювати посилання</button><button className="secondary full" onClick={() => window.print()}>Надрукувати QR</button></>}<button className="primary full" onClick={onClose}>Готово</button>{table.qrToken && <button className="cancel" disabled={loading} onClick={onRotate}>{loading ? "Оновлюємо…" : "Перевипустити QR"}</button>}</section></div> }
