"use client";

import { useMemo, useState } from "react";
import { Money } from "./Money";

type View = "pin" | "floor" | "order";
type MenuItem = { id: string; name: string; amountKopecks: number; category: string };
const menu: MenuItem[] = [
  { id: "burger", name: "Бургер з трюфельним соусом", amountKopecks: 32000, category: "Основне" }, { id: "fries", name: "Картопля фрі", amountKopecks: 14000, category: "Закуски" }, { id: "lemonade", name: "Лимонад цитрусовий", amountKopecks: 12000, category: "Напої" }, { id: "steak", name: "Стейк Ribeye", amountKopecks: 66000, category: "Основне" }, { id: "caesar", name: "Салат Цезар", amountKopecks: 28000, category: "Салати" }
];

export function StaffExperience() {
  const [view, setView] = useState<View>("pin"); const [pin, setPin] = useState(""); const [items, setItems] = useState(menu.slice(0, 3)); const [payment, setPayment] = useState<"idle" | "paying" | "paid">("idle");
  const total = useMemo(() => items.reduce((sum, item) => sum + item.amountKopecks, 0), [items]);
  const requestBill = () => { setPayment("paying"); window.setTimeout(() => setPayment("paid"), 1_200); };
  const add = (item: MenuItem) => setItems((current) => current.some((entry) => entry.id === item.id) ? current : [...current, item]);
  if (view === "pin") return <section className="screen pin"><p className="eyebrow">ПАНЕЛЬ ОФІЦІАНТА</p><h1>Вітаємо, Анно</h1><p>Введіть 4-значний PIN для початку зміни.</p><div className="pin-dots" aria-label={`Введено цифр: ${pin.length} з 4`}>{[0, 1, 2, 3].map((digit) => <i className={pin.length > digit ? "filled" : ""} key={digit} />)}</div><div className="pin-pad">{[1,2,3,4,5,6,7,8,9].map((number) => <button key={number} onClick={() => pin.length < 4 && setPin(`${pin}${number}`)}>{number}</button>)}<span /><button onClick={() => pin.length < 4 && setPin(`${pin}0`)}>0</button><button aria-label="Видалити цифру" onClick={() => setPin(pin.slice(0, -1))}>⌫</button></div><button className="primary staff-enter" disabled={pin.length !== 4} onClick={() => setView("floor")}>Відкрити зміну</button></section>;
  if (view === "order") return <section className="screen staff-order"><button className="back" onClick={() => setView("floor")} aria-label="Назад до залу">←</button><div className="order-heading"><div><p className="eyebrow">ОСНОВНИЙ ЗАЛ · 2 ГОСТЯ</p><h1>Стіл 02</h1></div><span className={payment === "paid" ? "paid-badge" : "work-badge"}>{payment === "paid" ? "✓ СПЛАЧЕНО" : payment === "paying" ? "◌ ОПЛАТА" : "● В РОБОТІ"}</span></div><div className="order-total"><span>Поточний рахунок</span><Money amountKopecks={total} size="lg" /><small>Анна · оновлено щойно</small></div><p className="label">ЗАМОВЛЕННЯ</p><div className="staff-items">{items.map((item) => <div className="staff-item" key={item.id}><span>{item.name}<small>1 × <Money amountKopecks={item.amountKopecks} /></small></span><Money amountKopecks={item.amountKopecks} /><button aria-label={`Видалити ${item.name}`} onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))}>−</button></div>)}</div><p className="label">ДОДАТИ ПОЗИЦІЮ</p><div className="add-menu">{menu.filter((item) => !items.some((entry) => entry.id === item.id)).map((item) => <button key={item.id} onClick={() => add(item)}><span>{item.name}<small>{item.category} · <Money amountKopecks={item.amountKopecks} /></small></span><b>＋</b></button>)}</div>{payment === "paid" ? <button className="primary full" onClick={() => { setPayment("idle"); setView("floor"); }}>Закрити стіл</button> : <button className="primary full" disabled={payment === "paying" || !items.length} onClick={requestBill}>{payment === "paying" ? "Очікуємо оплату…" : "Позвати рахунок"}</button>}</section>;
  const tables = [{ id: "01", state: "Вільний", className: "" }, { id: "02", state: payment === "paid" ? "Сплачено" : payment === "paying" ? "Оплачується" : `${(total / 100).toLocaleString("uk-UA")} ₴`, className: payment === "paying" ? "paying" : payment === "paid" ? "paid" : "busy" }, { id: "03", state: "680,00 ₴", className: "busy" }, { id: "04", state: "Оплачується", className: "paying" }, { id: "05", state: "Сплачено", className: "paid" }, { id: "06", state: "Вільний", className: "" }];
  return <section className="screen"><p className="eyebrow">ЗМІНА · АННА</p><div className="floor-title"><h1>Зал</h1><button className="primary add-table" aria-label="Додати стіл">＋</button></div><div className="zone-tabs"><button className="zone active">Основний зал</button><button className="zone">Тераса</button></div><div className="floor-grid">{tables.map((table) => <button key={table.id} className={`table-card ${table.className}`} onClick={() => setView("order")}><strong>{table.id}</strong><small>{table.state}</small><em>{table.className === "busy" ? "● Зайнятий · 28 хв" : table.className === "paying" ? "◌ Банк обробляє платіж" : table.className === "paid" ? "✓ Рахунок закрито" : "○ Готовий до гостей"}</em></button>)}</div>{payment === "paid" && <div className="payment-toast" role="status"><span>✓</span><p><b>Стіл 02 сплатив рахунок</b><small>Чайові: 124,00 ₴</small></p></div>}</section>;
}
