"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertIcon, ArrowLeftIcon, ArrowRightIcon, BackspaceIcon, BellIcon, CheckIcon, CloseIcon, FloorIcon, MenuIcon, MinusIcon, OrdersIcon, PlusIcon, SearchIcon, ShiftIcon } from "./StaffIcons";
import { Money } from "./Money";
import { subscribeToStaffEvents, type StaffRealtimeEvent } from "../lib/staff-realtime";
import { readStaffSession, StaffApiError, staffApi, storeStaffSession } from "../lib/staff-api";

type View = "pin" | "floor" | "order"; type Event = StaffRealtimeEvent & { seen?: boolean };
const items = [{ id:"burger", name:"Бургер з трюфельним соусом", price:32000 },{ id:"fries",name:"Картопля фрі",price:14000 },{ id:"lemonade",name:"Лимонад цитрусовий",price:12000 },{ id:"steak",name:"Стейк Ribeye",price:66000 }];
const tables = [{id:"01",state:"free",info:"Вільний 14 хв"},{id:"02",state:"busy",amount:58000,info:"2 гості · 28 хв",note:"Просить рахунок"},{id:"03",state:"busy",amount:68000,info:"4 гості · 12 хв"},{id:"04",state:"paying",amount:124000,info:"Банк підтверджує"},{id:"05",state:"paid",amount:94000,info:"Закрито 3 хв"},{id:"06",state:"free",info:"Вільний 6 хв"}];
const seed: Event[] = [{id:"demo-bill",type:"bill_requested",occurredAt:new Date().toISOString(),venueId:"demo",table:{id:"02",label:"02"},title:"Стіл 02 просить рахунок",body:"2 гості · 28 хв у залі",action:{label:"Відкрити стіл",kind:"open_table"}},{id:"demo-paid",type:"payment_succeeded",occurredAt:new Date().toISOString(),venueId:"demo",table:{id:"05",label:"05"},amountKopecks:94000,tipKopecks:18000,title:"Стіл 05 оплатив рахунок",body:"Чайові 180,00 ₴",action:{label:"Готово",kind:"resolve"}}];

export function StaffExperience(){
 const [view,setView]=useState<View>("pin"),[pin,setPin]=useState(""),[selected,setSelected]=useState("02"),[order,setOrder]=useState(items.slice(0,3)),[open,setOpen]=useState(false),[events,setEvents]=useState(seed),[connection,setConnection]=useState("offline"),[signingIn,setSigningIn]=useState(false),[loginError,setLoginError]=useState(""),[floorSnapshot,setFloorSnapshot]=useState<Awaited<ReturnType<typeof staffApi.getFloorSnapshot>>|null>(null),[floorError,setFloorError]=useState(""),[serverOrder,setServerOrder]=useState<Awaited<ReturnType<typeof staffApi.getOrder>>|null>(null),[serverMenu,setServerMenu]=useState<Awaited<ReturnType<typeof staffApi.getMenuItems>>["menuItems"]>([]),[savingOrder,setSavingOrder]=useState(false),[orderError,setOrderError]=useState("");
 const total=useMemo(()=>serverOrder?serverOrder.outstandingFoodKopecks:order.reduce((s,x)=>s+x.price,0),[order,serverOrder]); const unread=events.filter(x=>!x.seen).length; const displayedItems=serverOrder?serverOrder.items.map(item=>({id:item.id,name:item.name,price:item.unitPriceKopecks,quantity:item.quantity})):order.map(item=>({...item,quantity:1}));
 useEffect(()=>subscribeToStaffEvents({onState:setConnection,onEvent:event=>{setEvents(current=>current.some(x=>x.id===event.id)?current:[event,...current]);const session=readStaffSession();if(session)staffApi.getFloorSnapshot(session.token).then(setFloorSnapshot).catch(()=>undefined);}}),[]);
 useEffect(()=>{if(view!=="floor")return;const session=readStaffSession();if(!session)return;staffApi.getFloorSnapshot(session.token).then(setFloorSnapshot).catch(error=>setFloorError(error instanceof StaffApiError?error.message:"Не вдалося оновити зал"));},[view]);
 const openTable=async(id:string,orderId?:string)=>{setSelected(id);setView("order");setOpen(false);setServerOrder(null);setServerMenu([]);setOrderError("");const session=readStaffSession();if(orderId&&session){try{const nextOrder=await staffApi.getOrder(orderId,session.token);setServerOrder(nextOrder);if(session.staff.venueId){const menu=await staffApi.getMenuItems(session.staff.venueId,session.token);setServerMenu(menu.menuItems);}}catch(error){setFloorError(error instanceof StaffApiError?error.message:"Не вдалося завантажити замовлення");}}}; const resolve=(id:string)=>setEvents(current=>current.filter(x=>x.id!==id)); const seen=(id:string)=>setEvents(current=>current.map(x=>x.id===id?{...x,seen:true}:x)); const startShift=async()=>{const venueId=process.env.NEXT_PUBLIC_STAFF_VENUE_ID;if(!venueId){if(process.env.NODE_ENV!=="production"){setView("floor");return;}setLoginError("Не налаштовано venue для входу");return;}setSigningIn(true);setLoginError("");try{storeStaffSession(await staffApi.loginWithPin(venueId,pin));setView("floor");}catch(error){setLoginError(error instanceof StaffApiError?error.message:"Не вдалося увійти. Спробуйте ще раз.");setPin("");}finally{setSigningIn(false);}}; const mutateOrder=async(operation:"add"|"remove"|"bill", itemId?:string)=>{if(!serverOrder)return;const session=readStaffSession();if(!session)return;setSavingOrder(true);setOrderError("");try{const next=operation==="bill"?await staffApi.requestBill(serverOrder.id,serverOrder.version,session.token):await staffApi.updateOrder(serverOrder.id,serverOrder.version,[operation==="add"?{type:"add",menuItemId:itemId!,quantity:1}:{type:"remove",orderItemId:itemId!}],session.token);setServerOrder(next);}catch(error){setOrderError(error instanceof StaffApiError?error.message:"Не вдалося зберегти замовлення");}finally{setSavingOrder(false);}};
 if(view==="pin")return <section className="screen pin staff-pin"><p className="eyebrow">RIMVO · ПАНЕЛЬ ОФІЦІАНТА</p><h1>Вітаємо, Анно</h1><p>Введіть PIN для початку зміни.</p>{loginError&&<p role="alert">{loginError}</p>}<div className="pin-dots">{[0,1,2,3].map(i=><i className={pin.length>i?"filled":""} key={i}/>)}</div><div className="pin-pad">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} disabled={signingIn} onClick={()=>pin.length<4&&setPin(`${pin}${n}`)}>{n}</button>)}<span/><button disabled={signingIn} onClick={()=>pin.length<4&&setPin(`${pin}0`)}>0</button><button disabled={signingIn} onClick={()=>setPin(pin.slice(0,-1))}><BackspaceIcon/></button></div><button className="primary staff-enter" disabled={pin.length!==4||signingIn} onClick={startShift}>{signingIn?"Входимо…":"Відкрити зміну"} <ArrowRightIcon/></button></section>;
 if(view==="order")return <section className="screen staff-order"><button className="back" onClick={()=>setView("floor")}><ArrowLeftIcon/></button><div className="order-heading"><div><p className="eyebrow">ОСНОВНИЙ ЗАЛ · 2 ГОСТЯ</p><h1>Стіл {selected}</h1></div><span className="work-badge">{serverOrder?.status==="bill_requested"?"РАХУНОК ГОТОВИЙ":"В РОБОТІ"}</span></div><div className="order-total"><span>Поточний рахунок</span><Money amountKopecks={total} size="lg"/><small>{serverOrder?`Версія ${serverOrder.version} · ${serverOrder.status}`:"Анна · оновлено щойно"}</small></div>{orderError&&<p role="alert">{orderError}</p>}<p className="label">ЗАМОВЛЕННЯ</p><div className="staff-items">{displayedItems.map(x=><div className="staff-item" key={x.id}><span>{x.name}<small>{x.quantity} × <Money amountKopecks={x.price}/></small></span><Money amountKopecks={x.price*x.quantity}/><button disabled={savingOrder} onClick={()=>serverOrder?mutateOrder("remove",x.id):setOrder(c=>c.filter(i=>i.id!==x.id))}><MinusIcon/></button></div>)}</div><p className="label">ДОДАТИ ПОЗИЦІЮ</p><div className="add-menu">{serverOrder?serverMenu.filter(menuItem=>!serverOrder.items.some(orderItem=>orderItem.menuItemId===menuItem.id)).map(menuItem=><button disabled={savingOrder||serverOrder.status!=="open"} key={menuItem.id} onClick={()=>mutateOrder("add",menuItem.id)}><span>{menuItem.name}<small><Money amountKopecks={menuItem.unitPriceKopecks}/></small></span><b><PlusIcon/></b></button>):items.filter(x=>!order.some(i=>i.id===x.id)).map(x=><button key={x.id} onClick={()=>setOrder(c=>[...c,x])}><span>{x.name}<small><Money amountKopecks={x.price}/></small></span><b><PlusIcon/></b></button>)}</div><button className="primary full" disabled={savingOrder||serverOrder?.status==="bill_requested"} onClick={()=>serverOrder?mutateOrder("bill"):undefined}>{savingOrder?"Зберігаємо…":serverOrder?.status==="bill_requested"?"Рахунок запитано":"Позвати рахунок"} <ArrowRightIcon/></button></section>;
 const liveTables=floorSnapshot?floorSnapshot.floors.flatMap(floor=>floor.tables.map(table=>({id:table.id,label:table.label,state:table.status==="occupied"?"busy":table.status,amount:table.activeOrder?.outstandingFoodKopecks,orderId:table.activeOrder?.id,info:table.activeOrder?`Оновлено ${new Intl.DateTimeFormat("uk-UA",{hour:"2-digit",minute:"2-digit"}).format(new Date(table.activeOrder.updatedAt))}`:"Готовий до гостей"}))):tables.map(table=>({...table,label:table.id,orderId:undefined}));
 return <section className="staff-workspace"><aside className="staff-sidebar"><div className="staff-person"><span className="staff-avatar">А</span><div><b>Анна Коваль</b><small>Зміна з 10:00</small></div></div><nav><button className="active"><FloorIcon/>Зал</button><button><OrdersIcon/>Замовлення</button><button><MenuIcon/>Меню</button><button><ShiftIcon/>Зміна</button></nav><div className="shift-summary"><p>МОЯ ЗМІНА</p><strong>12 480 ₴</strong><small>7 столів · 1 240 ₴ чайових</small></div></aside><main className="staff-main"><div className="staff-mobile-head"><div><p className="eyebrow">ЗМІНА · АННА</p><h1>Зал</h1></div><Bell open={open} unread={unread} onClick={()=>setOpen(!open)}/></div><div className="staff-desktop-head"><div><p className="eyebrow">ОСНОВНИЙ ЗАЛ · ОНЛАЙН {connection==="connected"?"●":"○"}</p><h1>Зал ресторану</h1></div><div className="staff-actions"><button className="quiet-button"><SearchIcon/>Пошук</button><Bell open={open} unread={unread} onClick={()=>setOpen(!open)}/><button className="primary"><PlusIcon/>Новий стіл</button></div></div>{floorError&&<p role="status">{floorError}</p>}<div className="staff-overview"><div><b>{liveTables.filter(table=>table.state==="busy").length}</b><small>у залі</small></div><div><b>{liveTables.filter(table=>table.state==="paying").length}</b><small>оплачують</small></div><div><b>{liveTables.filter(table=>table.state==="free").length}</b><small>вільні</small></div><div><b>1 240 ₴</b><small>чайових сьогодні</small></div></div><div className="zone-tabs"><button className="zone active">Основний зал · {liveTables.length}</button><button className="zone">Тераса · 4</button></div><div className="floor-grid">{liveTables.map(t=><button className={`table-card ${t.state}`} key={t.id} onClick={()=>openTable(t.id,t.orderId)}><div className="table-card-head"><strong>{t.label}</strong><span>{t.state==="busy"?"У залі":t.state==="paying"?"Оплата":t.state==="paid"?"Сплачено":"Вільний"}</span></div><small>{t.amount?<Money amountKopecks={t.amount}/>:"Без рахунку"}</small><em>{t.info}</em></button>)}</div></main><Inbox open={open} events={events} onClose={()=>setOpen(false)} onOpen={id=>openTable(id)} onSeen={seen} onResolve={resolve}/><nav className="staff-bottom-nav"><button className="active"><FloorIcon/>Зал</button><button><OrdersIcon/>Замовлення</button><button onClick={()=>setOpen(!open)}><BellIcon/>Сповіщення</button><button><ShiftIcon/>Зміна</button></nav></section>;
}
function Bell({unread,onClick}:{open:boolean;unread:number;onClick:()=>void}){return <button className="staff-bell" onClick={onClick}><BellIcon/>{unread>0&&<b>{unread}</b>}</button>}
function Inbox({open,events,onClose,onOpen,onSeen,onResolve}:{open:boolean;events:Event[];onClose:()=>void;onOpen:(label:string,orderId?:string)=>void;onSeen:(id:string)=>void;onResolve:(id:string)=>void}){return <aside className={open?"staff-feed":"staff-feed collapsed"}><div className="feed-head"><div><p className="eyebrow">АКТИВНІ ПОДІЇ · {events.length}</p><h2>Сповіщення</h2></div><button onClick={onClose}><CloseIcon/></button></div>{events.length===0?<div className="notification"><span><CheckIcon/></span><div><b>Немає активних подій</b><p>Нові події з’являться тут одразу.</p></div></div>:events.map(event=><div className={`notification ${event.type==="bill_requested"?"urgent":""}`} key={event.id}><span>{event.type==="bill_requested"?<AlertIcon/>:<CheckIcon/>}</span><div><b>{event.title}</b><p>{event.body}</p><button onClick={()=>{onSeen(event.id);event.action?.kind==="open_table"?onOpen(event.table.label,event.orderId):onResolve(event.id)}}>{event.action?.label??"Готово"} <ArrowRightIcon/></button></div><time>{event.seen?"переглянуто":"щойно"}</time></div>)}</aside>}
